sudo: false
dist: trusty
group: deprecated

language: java

notifications:
  email: false

jdk:
  - oraclejdk8

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  - sha512sum -c apache-maven-3.6.3-bin.tar.gz.sha512
  - tar xzvf apache-maven-3.6.3-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.6.3/bin:$PATH
  - mvn -v

script:
  - mvn --version
  - mvn clean install
