sudo: false
dist: focal
group: deprecated

language: java

notifications:
  email: false

jdk:
  - oraclejdk17

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
  - sha512sum -c apache-maven-3.9.5-bin.tar.gz.sha512
  - tar xzvf apache-maven-3.9.5-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.9.5/bin:$PATH
  - mvn -v

script:
  - mvn --version
  # Skip unit test in CI
  - mvn clean install
